### ISSUE TITLE
game crashes with any mods loaded before i can even get to title screen

### ISSUE THREAD

**Issue by gdog637** [gurrenm3/BTD-Mod-Helper#106]
[17:08:47.575] [Il2CppAssemblyGenerator] [ERROR]
[17:08:47.603] [Il2CppAssemblyGenerator] [ERROR] Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: Object elements in a custom attribute signature should be either 'null' or an instance of BoxedArgument.
[17:08:47.604] [Il2CppAssemblyGenerator] [ERROR]    --- End of inner exception stack trace ---
[17:08:47.605] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
[17:08:47.607] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
[17:08:47.608] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
[17:08:47.609] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
[17:08:47.611] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
[17:08:47.612] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
[17:08:47.613] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
[17:08:47.614] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
[17:08:47.618] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
[17:08:47.620] [Il2CppAssemblyGenerator] [ERROR]    at Cpp2IL.Core.CorePlugin.AsmResolverDummyDllOutputFormat.DoOutput(ApplicationAnalysisContext context, String outputRoot) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AsmResolverDummyDllOutputFormat.cs:line 88
[17:08:47.622] [Il2CppAssemblyGenerator] [ERROR]    at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 436
[17:08:47.625] [Il2CppAssemblyGenerator] [ERROR]    at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 359

**Comment by doombubbles** [comment]
You likely need to update your MelonLoader. Here's more information: https://github.com/gurrenm3/BTD-Mod-Helper/wiki/Switching-to-MelonLoader-0.6.0
