### ISSUE TITLE
Can't launch the game with the BTD6modhleper

### ISSUE THREAD

**Issue by Flamingblade82** [gurrenm3/BTD-Mod-Helper#144]
[NewEntryPoint] Passing ptr to LoadAssemblyAndGetFuncPtr back to host...
[NewEntryPoint] Configuring imports...
[NewEntryPoint] Initializing. In default load context: True
[18:56:42.592] ------------------------------
[18:56:42.593] MelonLoader v0.6.1 Open-Beta
[18:56:42.594] OS: Windows 10
[18:56:42.594] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[18:56:42.594] ------------------------------
[18:56:42.594] Game Type: Il2cpp
[18:56:42.594] Game Arch: x64
[18:56:42.594] ------------------------------
[18:56:42.595] Core::BasePath = A:\SteamLibrary\steamapps\common\BloonsTD6
[18:56:42.595] Game::BasePath = A:\SteamLibrary\steamapps\common\BloonsTD6
[18:56:42.595] Game::DataPath = A:\SteamLibrary\steamapps\common\BloonsTD6\BloonsTD6_Data
[18:56:42.595] Game::ApplicationPath = A:\SteamLibrary\steamapps\common\BloonsTD6\BloonsTD6.exe
[18:56:42.595] Runtime Type: net6
[18:56:42.678] ------------------------------
[18:56:42.678] Game Name: BloonsTD6
[18:56:42.678] Game Developer: Ninja Kiwi
[18:56:42.680] Unity Version: 2021.3.16f1
[18:56:42.680] Game Version: 37.0
[18:56:42.681] ------------------------------

[NewEntryPoint] Caught exception invoking Initialize! System.TypeInitializationException: The type initializer for 'HarmonyLib.Harmony' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'
   at HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.Install()
   at HarmonyLib.Harmony..cctor()
   --- End of inner exception stack trace ---
   at HarmonyLib.Harmony..ctor(String id)
   at MelonLoader.Core.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 72
   at MelonLoader.NativeHost.MelonLoaderInvoker.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\MelonLoaderInvoker.cs:line 10
   at MelonLoader.NativeHost.NativeEntryPoint.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\NativeEntryPoint.cs:line 43

**Comment by doombubbles** [comment]
Your MelonLoader installation appears to have not fully succeeded, as it's missing one of the required libraries its meant to download. This kind of issue is fixed for most people by deleting their MelonLoader folder and reinstalling MelonLoader while having any anti virus/malware software disabled.

**Comment by Flamingblade82** [comment]
@doombubbles thank you so much btw can i still turn on my anti-virus on

**Comment by doombubbles** [comment]
Yeah, once everything is installed then anti-virus should not have any effect

**Comment by marc873a** [comment]
Mine just crashes when melon loader is checking "Game assembly". Tried reinstalling without antivirus but it unfortunately didn't work

**Comment by Flamingblade82** [comment]
@marc873a open the game without the anti virus

**Comment by marc873a** [comment]
@Flamingblade82 tried that but it didn't work

**Comment by marc873a** [comment]
Seems like it has something to do with the Epic games mod combat plugin:

...
[12:47:25.728] [BTD6_Epic_Games_Mod_Compat] Loading mods from C:\Program Files\Epic Games\BloonsTD6\Mods...
[12:47:25.739] [BTD6_Epic_Games_Mod_Compat] ------------------------------

[12:47:25.760] [BTD6_Epic_Games_Mod_Compat] Retargeting mods...
[12:47:25.762] [BTD6_Epic_Games_Mod_Compat] ------------------------------
---crash---
