### ISSUE TITLE
I can't install any mods or update the mod helper

### ISSUE THREAD

**Issue by CaSe2474** [gurrenm3/BTD-Mod-Helper#183]
When I try to, an error message shows up in the console saying
" [16:55:50.431] [BloonsTD6_Mod_Helper] Unhandled exception in coroutine. It will not continue executing.
System.MissingMethodException: Method not found: 'UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle`1<UnityEngine.GameObject> Il2CppAssets.Scripts.Unity.UI_New.Popups.PopupScreen.ShowPopup(Placement, System.String, System.String, ReturnCallback, System.String, ReturnCallback, System.String, TransitionAnim, BackGround, Boolean)'.
   at BTD_Mod_Helper.Api.ModHelperGithub.<>c__DisplayClass38_0.<DownloadLatest>b__0(PopupScreen screen)
   at BTD_Mod_Helper.Extensions.PopupScreenExt.<>c__DisplayClass4_0.<SafelyQueue>b__0()
   at BTD_Mod_Helper.Api.TaskScheduler.Coroutine(Action action, ScheduleType scheduleType, Int32 amountToWait, Func`1 waitCondition)+MoveNext()
   at MelonLoader.Support.MonoEnumeratorWrapper.MoveNext() in D:\a\MelonLoader\MelonLoader\Dependencies\SupportModules\Il2Cpp\MonoEnumeratorWrapper.cs:line 51", can someone help with this

**Comment by doombubbles** [comment]
If you haven't played with mods in a while you should try manually downloading the latest release https://github.com/gurrenm3/BTD-Mod-Helper/releases/tag/3.1.14

**Comment by Splatter23** [comment]
how to bypass microsoft defense from defense to download mod helper
