### ISSUE TITLE
game won't start

### ISSUE THREAD

**Issue by Crandall0** [gurrenm3/BTD-Mod-Helper#185]
melonloader shows this issue and then closes the game:

[Detailed_Descriptions] System.MissingMethodException: Method not found: 'Void Il2CppAssets.Scripts.Unity.UI_New.Upgrade.UpgradeScreen.UpdateUi(System.String)'.
   at DetailedDescriptions.DetailedDescriptionsMod.OnUpdate()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143

**Comment by doombubbles** [comment]
I don't really plan to be keeping Detailed Descriptions up to date myself, I've instead moved in favor of the in game wiki quick access feature of Useful Utilities https://github.com/doombubbles/useful-utilities
