### ISSUE TITLE
Data-Export don't work

### ISSUE THREAD

**Issue by TagerTi** [gurrenm3/BTD-Mod-Helper#214]
If I click on export game data the console says 
"
Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Boolean Il2CppSystem.Guid.TryParse(System.String, Il2CppSystem.Guid ByRef)'.
   at BTD_Mod_Helper.Api.Helpers.GameModelExporter.ExportAll()
   at BTD_Mod_Helper.MelonMain.<>c.<.cctor>b__31_2()
   at BTD_Mod_Helper.Api.ModOptions.ModSettingButton.<CreateComponent>b__6_0()
   at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )
"

**Comment by doombubbles** [comment]
Can you post the full log so I can see your platform details what mods you have active?
