### ISSUE TITLE
Whenever I try to open BTD6, a error code appears.

### ISSUE THREAD

**Issue by ghostesy** [gurrenm3/BTD-Mod-Helper#218]
This is the one in specific:
[17:20:30.432] SHA256 Hash: '396238a85906299166fe53f2ef6ecc5cf22faa38ca07ebb197fec0de32b9c276'
[NewEntryPoint] Caught exception invoking Start! System. IO.FileNotFoundException: Could not load file or assembly 'Assem
bly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
at System. Reflection. CustomAttribute ._ CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCto
r, Byte ** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
at System. Reflection. CustomAttribute.AddCustomAttributes(ListBuilder 1& attributes, RuntimeModule decoratedModule, In
t32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder 1 derivedAttributes)
at System. Reflection. CustomAttribute. GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken,
Int32 pcaCount, RuntimeType attributeFilterType)
at System.Reflection.CustomAttribute. GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
at System. Reflection. RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
at System.Attribute. GetCustomAttributes(Assembly element, Boolean inherit)
at MelonLoader.MelonUtils.PullAttributesFromAssembly[T] (Assembly asm, Boolean inherit) in D: \a\MelonLoader\MelonLoade
r\MelonLoader\MelonUtils.cs:line 216
at MelonLoader.MelonAssembly. LoadMelons() in D: \a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonAssembly.cs:line 22

at MelonLoader.MelonHandler. LoadMelonsFromDirectory[T](String path) in D:\a\MelonLoader\MelonLoader\MelonLoader \Melon
s\MelonHandler.cs:line 62
at MelonLoader.Core.Start() in D: \a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 117
at MelonLoader. NativeHost. NativeEntryPoint.Start() in D: \a\MelonLoader\MelonLoader \MelonLoader.NativeHost \NativeEntry
Point.cs:line 75

**Comment by ghostesy** [comment]
Wrong one, but that also happens. This is what happens whenever I install MelonLoader and nothing else. [NewEntryPoint] Caught exception invoking Initialize! System.TypeInitializationException: The type initializer for 'HarmonyLib.Harmony' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'
   at HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.Install()
   at HarmonyLib.Harmony..cctor()
   --- End of inner exception stack trace ---
   at HarmonyLib.Harmony..ctor(String id)
   at MelonLoader.Core.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 76
   at MelonLoader.NativeHost.MelonLoaderInvoker.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\MelonLoaderInvoker.cs:line 10
   at MelonLoader.NativeHost.NativeEntryPoint.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\NativeEntryPoint.cs:line 43
