### ISSUE TITLE
Mods arent appearing

### ISSUE THREAD

**Issue by lextre3445** [gurrenm3/BTD-Mod-Helper#226]
ive been getting this issue ever since i downloaded the paragon banana farm mod
System.TypeLoadException: Could not load type 'Il2CppNinjaKiwi.Common.ResourceUtils.SpriteReference' from assembly 'Il2CppNinjaKiwi.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at BTD_Mod_Helper.UI.Modded.ModsButton.Create(MainMenu mainMenu)
   at BTD_Mod_Helper.Patches.UI.MainMenu_Start.Postfix(MainMenu __instance)
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.Main.MainMenu::Start>(MainMenu this)
   at (il2cpp -> managed) Start(IntPtr , Il2CppMethodInfo* )

how do i fix it?

**Comment by doombubbles** [comment]
The creator of the mod will have to update their mod for v42
