### ISSUE TITLE
Game crashses on startup

### ISSUE THREAD

**Issue by Symmettry** [gurrenm3/BTD-Mod-Helper#234]
game crashes on startup whenever the btd6 mod helper dll is in. It does not crash when the DLL is not in the mods folder.

[NewEntryPoint] Caught exception invoking Initialize! System.TypeInitializationException: The type initializer for 'HarmonyLib.Harmony' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'
   at HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.Install()
   at HarmonyLib.Harmony..cctor()
   --- End of inner exception stack trace ---
   at HarmonyLib.Harmony..ctor(String id)
   at MelonLoader.Core.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 76
   at MelonLoader.NativeHost.MelonLoaderInvoker.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\MelonLoaderInvoker.cs:line 10
   at MelonLoader.NativeHost.NativeEntryPoint.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\NativeEntryPoint.cs:line 43

**Comment by doombubbles** [comment]
That's a MelonLoader library that is missing, which means MelonLoader didn't install correctly and you'll have to reinstall it. The most common culprit is needing to turn off antivirus software

**Comment by Symmettry** [comment]
ty
