### ISSUE TITLE
when i load in and click start i get a loading screen forever

### ISSUE THREAD

**Issue by Strealstud** [gurrenm3/BTD-Mod-Helper#254]
# Bug
game gets stuck on loadinf screen with error  [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Void Il2CppAssets.Scripts.Unity.UI_New.Popups.PopupScreen.set_hasSeenModderWarning(Boolean)'.
   at BTD_Mod_Helper.Patches.Popups.PopupScreen_ShowModderPopup.Prefix(PopupScreen __instance)
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.Popups.PopupScreen::ShowModderPopup>(PopupScreen this)
   at (il2cpp -> managed) ShowModderPopup(IntPtr , Il2CppMethodInfo* )
### Game Version
Newest

### MelonLoader Version

0.6.1

### Mod Helper Version
newest

### Description

When i load in i get stuck on a loading screen after i click start of a golden monkey 

### Logs

[NewEntryPoint] Passing ptr to LoadAssemblyAndGetFuncPtr back to host...
[NewEntryPoint] Configuring imports...
[NewEntryPoint] Initializing. In default load context: True
[17:29:25.820] ------------------------------
[17:29:25.820] MelonLoader v0.6.1 Open-Beta
[17:29:25.822] OS: Windows 10
[17:29:25.822] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[17:29:25.822] ------------------------------
[17:29:25.823] Game Type: Il2cpp
[17:29:25.823] Game Arch: x64
[17:29:25.823] ------------------------------
[17:29:25.824] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[17:29:25.824] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[17:29:25.824] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6_Data
[17:29:25.825] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6.exe
[17:29:25.825] Runtime Type: net6
[17:29:25.927] ------------------------------
[17:29:25.927] Game Name: BloonsTD6
[17:29:25.932] Game Developer: Ninja Kiwi
[17:29:25.934] Unity Version: 2022.3.20f1
[17:29:25.934] Game Version: UNKNOWN
[17:29:25.935] ------------------------------

[17:29:26.933] Preferences Loaded!

[17:29:26.981] Loading Plugins from 'C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\Plugins'...
[17:29:26.983] 0 Plugins loaded.
[NewEntryPoint] PreStarting.
[17:29:27.950] Loading Il2CppAssemblyGenerator...
[17:29:28.025] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[17:29:28.309] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[17:29:28.309] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[17:29:28.311] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[17:29:28.314] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[17:29:28.335] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.10
[17:29:28.335] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.5
[17:29:28.337] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2022.3.20
[17:29:28.340] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[17:29:28.341] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[17:29:28.342] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[17:29:28.342] [Il2CppAssemblyGenerator] Checking GameAssembly...
[17:29:28.705] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.
[NewEntryPoint] Starting.

[17:29:28.711] Loading Mods from 'C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\Mods'...
[17:29:28.713] ------------------------------
[17:29:28.816] Melon Assembly loaded: '.\Mods\Btd6ModHelper.dll'
[17:29:28.816] SHA256 Hash: '687fdaa2ce748572f7e0b1755103ef34a9232489fb3ce0e390e69c531a5af8bb'

[17:29:36.796] ------------------------------
[17:29:36.797] BloonsTD6 Mod Helper v3.1.21
[17:29:36.797] by Gurrenm4 and Doombubbles
[17:29:36.798] Assembly: Btd6ModHelper.dll
[17:29:36.801] ------------------------------
[17:29:36.802] ------------------------------
[17:29:36.802] 1 Mod loaded.

[17:29:37.601] Class::Init signatures have been exhausted, using a substitute!
[17:29:37.641] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain[17:29:37.692] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[17:29:37.696] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[17:29:37.708] Support Module Loaded: C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[17:29:39.718] [BloonsTD6_Mod_Helper] Failed to apply BloonsTD6 Mod Helper patch(es) in IsModdedClientPatches: "Could not load type 'Il2CppAssets.Scripts.Unity.Modding' from assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'." The mod might not function correctly. This needs to be fixed by Gurrenm4 and Doombubbles
Setting breakpad minidump AppID = 960090
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561199562049725 [API loaded no]
[17:29:45.015] [BloonsTD6_Mod_Helper] Finished getting mods from github in background, found 299 mods over 4.9 seconds
[17:29:56.231] [BloonsTD6_Mod_Helper] Registering ModContent for BloonsTD6 Mod Helper...
[17:30:05.372] During invoking native->managed trampoline
[17:30:05.375] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Void Il2CppAssets.Scripts.Unity.UI_New.Popups.PopupScreen.set_hasSeenModderWarning(Boolean)'.
   at BTD_Mod_Helper.Patches.Popups.PopupScreen_ShowModderPopup.Prefix(PopupScreen __instance)
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.Popups.PopupScreen::ShowModderPopup>(PopupScreen this)
   at (il2cpp -> managed) ShowModderPopup(IntPtr , Il2CppMethodInfo* )

**Comment by doombubbles** [comment]
This is now fixed with the new update https://github.com/gurrenm3/BTD-Mod-Helper/releases/tag/3.1.22

**Comment by Strealstud** [comment]
no way so this was witerally just released?
