### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Randle833** [gurrenm3/BTD-Mod-Helper#260]
# Bug I was going to play a level with the mods and every time I load in it kept on saying. [14:32:12.120] [BloonsTD6_Mod_Helper] System.TypeInitializationException: The type initializer for 'OmegaCrosspathing.UI' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Utils.SpriteReference Il2CppAssets.Scripts.Data.Global.TowerBackgroundSprites.get_primarySprite()'.
   at OmegaCrosspathing.UI..cctor()
   --- End of inner exception stack trace ---
   at OmegaCrosspathing.Main.TowerSelectionMenu_Initialise(TowerSelectionMenu __instance)
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.InGame.TowerSelectionMenu.TowerSelectionMenu::Initialise>(TowerSelectionMenu this)
   at (il2cpp -> managed) Initialise(IntPtr , Il2CppMethodInfo* )
[14:32:12.632] During invoking native->managed trampoline
[14:32:12.642] [BloonsTD6_Mod_Helper] Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at Assets.Scripts.Unity.UI_New.InGame.InGame.StartMatch (Assets.Scripts.Models.Profile.MapSaveDataModel mapSaveData, System.Boolean wasSaveOverwritten) [0x00000] in <00000000000000000000000000000000>:0
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at DMD<Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame::StartMatch>(InGame this, MapSaveDataModel mapSaveData, Boolean wasSaveOverwritten)
   at (il2cpp -> managed) StartMatch(IntPtr , IntPtr , Byte , Il2CppMethodInfo* )

![Screenshot 2024-08-27 144258](https://github.com/user-attachments/assets/604e5731-aa6c-4e91-9194-b5cb55e5bf59)

**Comment by doombubbles** [comment]
This is an issue with OmegaCrosspathing, not Mod Helper
