### ISSUE TITLE
Problem regarding some in-game menus that come with mods

### ISSUE THREAD

**Issue by Unreal2100x** [gurrenm3/BTD-Mod-Helper#261]
# Bug

### Game Version

44.1

### MelonLoader Version

Latest

### Mod Helper Version

Latest

### Description

I need help with something regarding what is written in Logs. I can't access in-game menus that come with some mods. I get sent into what would seem like a menu, but it's the challenge menu, and I can't do anything.

### Logs

[20:24:21.096] ------------------------------
[20:24:21.267] MelonLoader v0.6.1 Open-Beta
[20:24:21.272] OS: Windows 11
[20:24:21.273] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[20:24:21.274] ------------------------------
[20:24:21.276] Game Type: Il2cpp
[20:24:21.277] Game Arch: x64
[20:24:21.277] ------------------------------
[20:24:21.278] Core::BasePath = C:\Users\dilja\Desktop\BTD6 v.44.1\Bloons TD 6
[20:24:21.279] Game::BasePath = C:\Users\dilja\Desktop\BTD6 v.44.1\Bloons TD 6
[20:24:21.280] Game::DataPath = C:\Users\dilja\Desktop\BTD6 v.44.1\Bloons TD 6\BloonsTD6_Data
[20:24:21.281] Game::ApplicationPath = C:\Users\dilja\Desktop\BTD6 v.44.1\Bloons TD 6\BloonsTD6.exe
[20:24:21.281] Runtime Type: net6
[20:24:21.672] ------------------------------
[20:24:21.673] Game Name: BloonsTD6
[20:24:21.675] Game Developer: Ninja Kiwi
[20:24:21.681] Unity Version: 2022.3.20f1
[20:24:21.682] Game Version: UNKNOWN
[20:24:21.683] ------------------------------

[20:24:24.335] Preferences Loaded!

[20:24:24.407] Loading Plugins from 'C:\Users\dilja\Desktop\BTD6 v.44.1\Bloons TD 6\Plugins'...
[20:24:24.414] 0 Plugins loaded.
[20:24:27.473] Loading Il2CppAssemblyGenerator...
[20:24:27.567] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[20:24:28.196] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[20:24:28.197] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[20:24:28.199] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[20:24:28.201] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[20:24:28.252] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.10
[20:24:28.253] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.5
[20:24:28.262] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2022.3.20
[20:24:28.265] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[20:24:28.268] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[20:24:28.270] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[20:24:28.287] [Il2CppAssemblyGenerator] Checking GameAssembly...
[20:24:28.978] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.

[20:24:28.999] Loading Mods from 'C:\Users\dilja\Desktop\BTD6 v.44.1\Bloons TD 6\Mods'...
[20:24:29.015] ------------------------------
[20:24:29.048] Melon Assembly loaded: '.\Mods\BetterAutoStart.dll'
[20:24:29.058] SHA256 Hash: '92f8eba2bb0b4e55fbccfb64cd109590eba38081e48159aa00507888ea61af63'
[20:24:29.221] Melon Assembly loaded: '.\Mods\Btd6ModHelper.dll'
[20:24:29.222] SHA256 Hash: 'd339ad7ec25e48ce20389941252c19667c9eea89bd861d7d6c4e8044a175c15b'
[20:24:29.246] Melon Assembly loaded: '.\Mods\ExtraBloons.dll'
[20:24:29.248] SHA256 Hash: '968eb877bcf7569f6317f75e49a40ce9df91da45b0618bc8edb762d189260fc1'
[20:24:29.265] Melon Assembly loaded: '.\Mods\FasterForward.dll'
[20:24:29.272] SHA256 Hash: 'c01e5ab5d798e3d0943f16f47529db94fe383de20170059223018ec0e663337d'
[20:24:29.321] Melon Assembly loaded: '.\Mods\TimeMachine.dll'
[20:24:29.323] SHA256 Hash: '120890fb966b884b77cd855868fef256256f53bf0b8d5a94d78fe5a3d889f494'

[20:24:31.118] ------------------------------
[20:24:31.120] Better Auto Start v1.1.2
[20:24:31.120] by doombubbles
[20:24:31.122] Assembly: BetterAutoStart.dll
[20:24:31.130] ------------------------------
[20:24:31.137] ------------------------------
[20:24:31.137] BloonsTD6 Mod Helper v3.2.0
[20:24:31.137] by Gurrenm4 and Doombubbles
[20:24:31.148] Assembly: Btd6ModHelper.dll
[20:24:31.150] ------------------------------
[20:24:31.157] ------------------------------
[20:24:31.159] All Extrabloons in Sandbox v0.1.0
[20:24:31.159] by Stiefanek
[20:24:31.161] Assembly: ExtraBloons.dll
[20:24:31.163] ------------------------------
[20:24:31.170] ------------------------------
[20:24:31.176] Faster Forward v1.1.2
[20:24:31.176] by doombubbles
[20:24:31.178] Assembly: FasterForward.dll
[20:24:31.181] ------------------------------
[20:24:31.188] ------------------------------
[20:24:31.190] Time Machine v1.1.0
[20:24:31.190] by doombubbles
[20:24:31.192] Assembly: TimeMachine.dll
[20:24:31.195] ------------------------------
[20:24:31.197] ------------------------------
[20:24:31.199] 5 Mods loaded.

[20:24:33.510] Class::Init signatures have been exhausted, using a substitute!
[20:24:33.593] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[20:24:33.711] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[20:24:33.734] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[20:24:33.764] Support Module Loaded: C:\Users\dilja\Desktop\BTD6 v.44.1\Bloons TD 6\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[20:24:42.189] [BloonsTD6_Mod_Helper] System.NullReferenceException: Object reference not set to an instance of an object.
   at BTD_Mod_Helper.Api.ModMenu.ModHelperHttp.DownloadFile(String url, String filePath)
[20:24:44.026] [BloonsTD6_Mod_Helper] Downloaded Btd6ModHelper.xml for v3.2.0
[20:24:49.800] [BloonsTD6_Mod_Helper] Finished getting mods from github in background, found 303 mods over 7.5 seconds
[20:25:12.108] [BloonsTD6_Mod_Helper] Registering ModContent for BloonsTD6 Mod Helper...
[20:25:22.870] During invoking native->managed trampoline
[20:25:22.875] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:25:42.500] During invoking native->managed trampoline
[20:25:42.501] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:25:45.085] During invoking native->managed trampoline
[20:25:45.085] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:25:45.611] During invoking native->managed trampoline
[20:25:45.612] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:25:46.576] During invoking native->managed trampoline
[20:25:46.577] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:25:48.494] During invoking native->managed trampoline
[20:25:48.495] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:25:52.582] During invoking native->managed trampoline
[20:25:52.583] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:25:57.172] During invoking native->managed trampoline
[20:25:57.172] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:02.537] During invoking native->managed trampoline
[20:26:02.538] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:03.696] During invoking native->managed trampoline
[20:26:03.697] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:05.152] During invoking native->managed trampoline
[20:26:05.152] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:10.745] [BloonsTD6_Mod_Helper] Backing up to C:\Users\dilja\Desktop\BTD6 v.44.1\Bloons TD 6\Mods\BloonsTD6 Mod Helper\Old Mods\BetterAutoStart.dll
[20:26:10.752] During invoking native->managed trampoline
[20:26:10.753] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:11.740] [BloonsTD6_Mod_Helper] Successfully downloaded BetterAutoStart.dll, remember to restart to apply the changes!
[20:26:13.058] During invoking native->managed trampoline
[20:26:13.059] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:13.817] During invoking native->managed trampoline
[20:26:13.818] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:15.266] During invoking native->managed trampoline
[20:26:15.267] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:18.773] During invoking native->managed trampoline
[20:26:18.774] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:19.896] During invoking native->managed trampoline
[20:26:19.897] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:23.857] During invoking native->managed trampoline
[20:26:23.858] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:24.085] During invoking native->managed trampoline
[20:26:24.086] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:24.231] During invoking native->managed trampoline
[20:26:24.232] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:24.400] During invoking native->managed trampoline
[20:26:24.402] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:24.522] During invoking native->managed trampoline
[20:26:24.523] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:24.643] During invoking native->managed trampoline
[20:26:24.644] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:24.771] During invoking native->managed trampoline
[20:26:24.772] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:24.934] During invoking native->managed trampoline
[20:26:24.936] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:25.041] During invoking native->managed trampoline
[20:26:25.042] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:25.348] During invoking native->managed trampoline
[20:26:25.349] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:25.464] During invoking native->managed trampoline
[20:26:25.466] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:25.558] During invoking native->managed trampoline
[20:26:25.560] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:25.721] During invoking native->managed trampoline
[20:26:25.722] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:25.829] During invoking native->managed trampoline
[20:26:25.831] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:25.927] During invoking native->managed trampoline
[20:26:25.929] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:26.009] During invoking native->managed trampoline
[20:26:26.010] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:26.109] During invoking native->managed trampoline
[20:26:26.110] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:26.171] During invoking native->managed trampoline
[20:26:26.172] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:26.272] During invoking native->managed trampoline
[20:26:26.274] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )
[20:26:26.514] During invoking native->managed trampoline
[20:26:26.514] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppAssets.Scripts.Unity.Bridge.UnityToSimulation Il2CppAssets.Scripts.Unity.UI_New.InGame.InGame.get_UnityToSimulation()'.
   at BetterAutoStart.BetterAutoStartMod.Button_OnPointerClick.Postfix(Button __instance, PointerEventData eventData)
   at DMD<UnityEngine.UI.Button::OnPointerClick>(Button this, PointerEventData eventData)
   at (il2cpp -> managed) OnPointerClick(IntPtr , IntPtr , Il2CppMethodInfo* )

**Comment by doombubbles** [comment]
Update Better Auto Start https://github.com/doombubbles/better-auto-start/releases/tag/1.1.3
