### ISSUE TITLE
wtf is this

### ISSUE THREAD

**Issue by kkkkk59912** [gurrenm3/BTD-Mod-Helper#275]
[15:52:07.553] ------------------------------
[15:52:07.585] MelonLoader v0.6.5 Open-Beta
[15:52:07.587] OS: Windows 10
[15:52:07.587] Hash Code: ECEE59E98250B37FBAD36ACD622C0C177FB65E478F6B3EE58F58366B6557DF70
[15:52:07.587] ------------------------------
[15:52:07.588] Game Type: Il2cpp
[15:52:07.588] Game Arch: x64
[15:52:07.588] ------------------------------
[15:52:07.589] Command-Line: C:\Users\Sound wave\Desktop\Nova mapa (2)\Bloons TD 6\BloonsTD6.exe
[15:52:07.589] ------------------------------
[15:52:07.590] Core::BasePath = C:\Users\Sound wave\Desktop\Nova mapa (2)\Bloons TD 6
[15:52:07.590] Game::BasePath = C:\Users\Sound wave\Desktop\Nova mapa (2)\Bloons TD 6
[15:52:07.590] Game::DataPath = C:\Users\Sound wave\Desktop\Nova mapa (2)\Bloons TD 6\BloonsTD6_Data
[15:52:07.590] Game::ApplicationPath = C:\Users\Sound wave\Desktop\Nova mapa (2)\Bloons TD 6\BloonsTD6.exe
[15:52:07.591] Runtime Type: net6
[15:52:07.732] ------------------------------
[15:52:07.733] Game Name: BloonsTD6
[15:52:07.733] Game Developer: Ninja Kiwi
[15:52:07.736] Unity Version: 2022.3.20f1
[15:52:07.736] Game Version: 44.1
[15:52:07.736] ------------------------------

[15:52:10.664] Preferences Loaded!

[15:52:10.785] Loading UserLibs from 'C:\Users\Sound wave\Desktop\Nova mapa (2)\Bloons TD 6\UserLibs'...

[15:52:10.800] Loading Plugins from 'C:\Users\Sound wave\Desktop\Nova mapa (2)\Bloons TD 6\Plugins'...
[15:52:10.803] 0 Plugins loaded.
[15:52:11.453] Loading Il2CppAssemblyGenerator...
[15:52:11.545] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[15:52:11.832] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[15:52:11.832] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[15:52:11.833] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[15:52:11.833] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[15:52:11.839] [Il2CppAssemblyGenerator] Using Cpp2IL Version: 2022.1.0-pre-release.18
[15:52:11.839] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.6-ci.545+3da49636029e18c88fe93901a893499a2d779805
[15:52:11.839] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2022.3.20
[15:52:11.840] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[15:52:11.841] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[15:52:11.842] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[15:52:11.842] [Il2CppAssemblyGenerator] Checking GameAssembly...
[15:52:12.090] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.

[15:52:12.094] Loading Mods from 'C:\Users\Sound wave\Desktop\Nova mapa (2)\Bloons TD 6\Mods'...
[15:52:12.095] ------------------------------
[15:52:12.215] Melon Assembly loaded: '.\Mods\Btd6ModHelper (1).dll'
[15:52:12.215] SHA256 Hash: '80F7EE741CF40374344760F70487DE7E2AE0A0E8935A5E39564B44369FDAB501'

[15:52:12.998] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'BloonsTD6 Mod Helper' is missing the following dependencies:
    - 'Il2CppNinjaKiwi.LiNK.Client' v50.0.2.0
[15:52:13.043] ------------------------------
[15:52:13.044] BloonsTD6 Mod Helper v3.3.0
[15:52:13.044] by Gurrenm4 and Doombubbles
[15:52:13.045] Assembly: Btd6ModHelper (1).dll
[15:52:13.045] ------------------------------
[15:52:13.046] ------------------------------
[15:52:13.046] 1 Mod loaded.

[15:52:14.555] [Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[15:52:14.746] [Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[15:52:14.835] [Il2CppInterop] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[15:52:14.919] [Il2CppInterop] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[15:52:14.932] Support Module Loaded: C:\Users\Sound wave\Desktop\Nova mapa (2)\Bloons TD 6\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[15:52:19.366] [BloonsTD6_Mod_Helper] Failed to apply BloonsTD6 Mod Helper patch(es) in TimeManager_FastForwardTimeScale: "Object reference not set to an instance of an object." The mod might not function correctly. This needs to be fixed by Gurrenm4 and Doombubbles
[15:52:19.367] [BloonsTD6_Mod_Helper] Failed to apply BloonsTD6 Mod Helper patch(es) in TimeManager_MaxSimulationStepsPerUpdate: "Object reference not set to an instance of an object." The mod might not function correctly. This needs to be fixed by Gurrenm4 and Doombubbles
[15:52:21.051] [BloonsTD6_Mod_Helper] HarmonyLib.HarmonyException: Patching exception in method null
 ---> System.TypeLoadException: Could not load type 'Il2CppNinjaKiwi.LiNK.Client.LiNKAccountControllers.SteamWebView' from assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at BTD_Mod_Helper.UI.BTD6.EmbeddedBrowser.SteamWebView_OnGUI.TargetMethods()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HarmonyLib.PatchClassProcessor.GetBulkMethods()
   at HarmonyLib.PatchClassProcessor.Patch()
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at BTD_Mod_Helper.MelonMain.OnInitialize()
   at BTD_Mod_Helper.BloonsMod.OnInitializeMelon()
   at MelonLoader.MelonBase.LoaderInitialized() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonBase.cs:line 440
[15:52:29.000] [BloonsTD6_Mod_Helper] Finished getting mods from github in background, found 305 mods over 8,5 seconds
[15:52:42.519] [Il2CppInterop] During invoking native->managed trampoline
[15:52:42.521] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppSystem.Collections.Generic.Dictionary`2<Il2CppNinjaKiwi.Common.ResourceUtils.AudioClipReference,UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationHandle`1<UnityEngine.AudioClip>> Il2CppAssets.Scripts.Unity.Audio.AudioFactory.get_audioClipHandles()'.
   at BTD_Mod_Helper.Patches.Resources.AudioFactory_Start.Postfix(AudioFactory __instance)
   at DMD<Il2CppAssets.Scripts.Unity.Audio.AudioFactory::Start>(AudioFactory this)
   at (il2cpp -> managed) Start(IntPtr , Il2CppMethodInfo* )
[15:52:42.528] [Il2CppInterop] During invoking native->managed trampoline
[15:52:42.530] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Double Il2CppAssets.Scripts.Utils.TimeManager.get_replayTimeScaleMultiplier()'.
   at BTD_Mod_Helper.Patches.Sim.TimeManager_Update.Postfix()
   at DMD<Il2CppAssets.Scripts.Utils.TimeManager::Update>(TimeManager this)
   at (il2cpp -> managed) Update(IntPtr , Il2CppMethodInfo* )

**Comment by doombubbles** [comment]
The new Mod Helper update is specifically for BloonsTD6 v45. If you're not using v45 yet then you need to continue using the previous version of Mod Helper
