### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by iojuedioe9rd** [gurrenm3/BTD-Mod-Helper#93]
[14:44:46.468] ------------------------------
[14:44:46.472] MelonLoader v0.5.5 Open-Beta
[14:44:46.473] OS: Windows 10
[14:44:46.474] Hash Code: 57545710048555350515452101521025297995653101559949575755515399509950
[14:44:46.474] ------------------------------
[14:44:46.476] Game Type: Il2Cpp
[14:44:46.479] Game Arch: x64
[14:44:46.479] ------------------------------
[14:44:46.480] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[14:44:46.481] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[14:44:46.482] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6_Data
[14:44:46.483] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6.exe

[14:44:47.028] ------------------------------
[14:44:47.030] Game Name: BloonsTD6
[14:44:47.034] Game Developer: Ninja Kiwi
[14:44:47.045] Unity Version: 2021.3.12f1
[14:44:47.046] Game Version: 34.2
[14:44:47.046] ------------------------------
[14:44:47.587] Preferences Loaded!
[14:44:47.592] [Il2CppUnityTls] Patching mono_unity_get_unitytls_interface...
[14:44:47.593] [Il2CppUnityTls] Patching il2cpp_unity_install_unitytls_interface...
[14:44:47.877] [Il2CppUnityTls] Calling Il2CppInstallUnityTlsInterface...

[14:44:47.900] Loading Plugins from 'C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\Plugins'...
[14:44:47.901] ------------------------------------------------------------------------------------------
[14:44:47.907] Melon Assembly loaded: '.\Plugins\CatsMods.dll'
[14:44:47.907] SHA256 Hash: 'bddf1a1104f0e1d83dcece27067bc277cadb01d8413fb88297e37ff61f04910c'

[14:44:47.963] ------------------------------
[14:44:47.963] CatsMods v1.0.0
[14:44:47.965] by Cats Studio
[14:44:47.966] Assembly: CatsMods.dll
[14:44:47.966] ------------------------------
[14:44:47.969] ------------------------------------------------------------------------------------------
[14:44:47.970] 1 Plugin loaded.

[14:44:48.450] [MelonStartScreen] Initializing...
[14:44:48.497] [MelonStartScreen] Using Start Screen Theme: "Default"
[14:44:49.718] Loading Il2CppAssemblyGenerator...
[14:44:49.743] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[14:44:50.035] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[14:44:50.036] [Il2CppAssemblyGenerator] RemoteAPI.UnhollowerVersion = null
[14:44:50.037] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[14:44:50.038] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[14:44:50.040] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[14:44:50.042] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.7
[14:44:50.043] [Il2CppAssemblyGenerator] Using Il2CppAssemblyUnhollower Version = 0.4.18.0
[14:44:50.045] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2021.3.12
[14:44:50.047] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[14:44:50.049] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[14:44:50.051] [Il2CppAssemblyGenerator] Il2CppAssemblyUnhollower is up to date.
[14:44:50.052] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[14:44:50.054] [Il2CppAssemblyGenerator] Checking GameAssembly...
[14:44:50.516] [Il2CppAssemblyGenerator] Assembly Generation Needed!
[14:44:50.520] [Il2CppAssemblyGenerator] Executing Cpp2IL...
[14:44:50.524] [Il2CppAssemblyGenerator] "C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\Cpp2IL.exe" --game-path "C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6" --exe-name "BloonsTD6" --use-processor attributeinjector --output-as dummydll
[14:44:50.587] [Il2CppAssemblyGenerator] ===Cpp2IL by Samboy063===
[14:44:50.588] [Il2CppAssemblyGenerator] A Tool to Reverse Unity's "il2cpp" Build Process.
[14:44:50.589] [Il2CppAssemblyGenerator] Version 2022.1.0-pre-release.7
[14:44:50.590] [Il2CppAssemblyGenerator]
[14:44:50.591] [Il2CppAssemblyGenerator] [Warn] [Program] NO_COLOR set, disabling ANSI color codes as you requested.
[14:44:50.593] [Il2CppAssemblyGenerator] [Info] [Program] Running on Win32NT
[14:44:50.701] [Il2CppAssemblyGenerator] [Info] [Plugins] Loading plugins from C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\Plugins...
[14:44:50.724] [Il2CppAssemblyGenerator] [Info] [Plugins] Using Plugin: Cpp2IL Built-In
[14:44:50.731] [Il2CppAssemblyGenerator] [Info] [Program] Determined game's unity version to be 2021.3.12a0
[14:44:50.782] [Il2CppAssemblyGenerator] [Info] [Library] Initializing Metadata...
[14:44:50.784] [Il2CppAssemblyGenerator] [Info] [Library]       Using actual IL2CPP Metadata version 29
[14:44:50.998] [Il2CppAssemblyGenerator] [Info] [Library] Initialized Metadata in 216ms
[14:44:51.000] [Il2CppAssemblyGenerator] [Info] [Library] Using binary type Portable Executable (from LibCpp2IL)
[14:44:51.003] [Il2CppAssemblyGenerator] [Info] [Library] Searching Binary for Required Data...
[14:44:51.276] [Il2CppAssemblyGenerator] [Info] [Library] Got Binary codereg: 0x182614590, metareg: 0x182A7B930 in 276ms.
[14:44:51.278] [Il2CppAssemblyGenerator] [Info] [Library] Initializing Binary...
[14:44:51.403] [Il2CppAssemblyGenerator] [Info] [Library] Initialized Binary in 127ms
[14:44:51.503] [Il2CppAssemblyGenerator] [Info] [Library] Mapping pointers to Il2CppMethodDefinitions...Processed 115037 OK (99ms)
[14:44:51.515] [Il2CppAssemblyGenerator] [Info] [Program] Creating application model...
[14:44:52.180] [Il2CppAssemblyGenerator] [Warn] [Program] StartOfNextFunc returned va 0xED76002C72660, raw address 0x0, for raw address 0x251F700. It should be more than raw address. Falling back to manual, slow, decompiler-based approach.
[14:44:52.268] [Il2CppAssemblyGenerator] [Warn] [Program] StartOfNextFunc returned va 0xED76002C72660, raw address 0x0, for raw address 0x251F700. It should be more than raw address. Falling back to manual, slow, decompiler-based approach.
[14:44:52.516] [Il2CppAssemblyGenerator] [Info] [Program] Application model created in 999.9931ms
[14:44:52.518] [Il2CppAssemblyGenerator] [Info] [Program] Pre-processing processing layers...
[14:44:52.519] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector...
[14:44:52.521] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector finished in 0ms
[14:44:52.522] [Il2CppAssemblyGenerator] [Info] [Program] Invoking processing layers...
[14:44:52.523] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector...
[14:44:53.263] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector finished in 745.6858ms
[14:44:53.265] [Il2CppAssemblyGenerator] [Info] [Program] Outputting as Stub ("Dummy") DLL Files to C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\cpp2il_out...
[14:44:57.203] [Il2CppAssemblyGenerator] [ERROR]
[14:44:57.218] [Il2CppAssemblyGenerator] [ERROR] Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: Object elements in a custom attribute signature should be either 'null' or an instance of BoxedArgument.
[14:44:57.221] [Il2CppAssemblyGenerator] [ERROR]    --- End of inner exception stack trace ---
[14:44:57.223] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
[14:44:57.225] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
[14:44:57.227] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
[14:44:57.230] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
[14:44:57.232] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
[14:44:57.235] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
[14:44:57.246] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
[14:44:57.248] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
[14:44:57.249] [Il2CppAssemblyGenerator] [ERROR]    at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
[14:44:57.251] [Il2CppAssemblyGenerator] [ERROR]    at Cpp2IL.Core.CorePlugin.AsmResolverDummyDllOutputFormat.DoOutput(ApplicationAnalysisContext context, String outputRoot) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AsmResolverDummyDllOutputFormat.cs:line 88
[14:44:57.255] [Il2CppAssemblyGenerator] [ERROR]    at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 436
[14:44:57.258] [Il2CppAssemblyGenerator] [ERROR]    at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 359

[14:44:58.776] Loading Mods from 'C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\Mods'...
[14:44:58.782] ------------------------------------------------------------------------------------
[14:44:58.833] Melon Assembly loaded: '.\Mods\Btd6ModHelper.dll'
[14:44:58.834] SHA256 Hash: 'cdfc25bc65b01066b8fad663826a05a4b5bfa6379b8d60282e9a5820d7b5f496'
Could not load signature of BTD_Mod_Helper.BloonsTD6Mod:OnConnected due to: Could not load file or assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>
[14:44:58.841] [ERROR] Failed to load 1 Melon from Btd6ModHelper.dll:
[14:44:58.843] [ERROR] Failed to load Melon 'BTD_Mod_Helper.MelonMain': Failed to create an instance of the Melon.
[14:44:58.847] [ERROR] System.TypeLoadException: VTable setup of type BTD_Mod_Helper.MelonMain failed
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00018] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000a8] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00020] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x00213] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00095] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture) [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0
  at MelonLoader.MelonAssembly.LoadMelons () [0x000c4] in <80a94e21ac074902a9d511c653789548>:0

[14:44:58.850] ------------------------------------------------------------------------------------
[14:44:58.855] 0 Mods loaded.

[14:44:58.863] [ERROR] No Support Module Loaded!
Facepunch.Steamworks Unity: WindowsPlayer
Facepunch.Steamworks Os: Windows
Facepunch.Steamworks Arch: x64
Setting breakpad minidump AppID = 960090
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561199122888751 [API loaded no]

**Comment by pcclub88** [comment]
they have not yet updated the mod helper for v34 so wait ig

**Comment by doombubbles** [comment]
To be even more clear, v34 has broken MelonLoader itself, and that will need an updated version before any mods can be updated.
